### ISSUE TITLE
单元测试失败

### ISSUE THREAD

**Issue by hstdt** [fatbobman/PersistentHistoryTrackingKit#1]
<img width="1414" alt="CleanShot 2022-10-25 at 19 13 35" src="https://user-images.githubusercontent.com/10215098/197758689-ea238142-d5d5-4c1f-bb32-07537dfc4af0.png">

我在尝试使用`NSPersistentHistoryToken`方式来记录上一次位置(还是觉得`Date()`可能不够准确，一个错误的时间是否会导致用户永远不会同步或被直接删除数据)，不过我下午才通过您的文章学习`PersistentHistory`，了解很少。想借助您的单元测试验证，但是现在单元测试通过不了，麻烦看看能否抽出时间修复一下，谢谢。

借鉴Apple的代码如下:
https://github.com/hstdt/AppleSamples/blob/d66a7ad5a4c8bb1d8bfd265c597ed6d2bf2c3ae4/SynchronizingALocalStoreToTheCloud/CoreDataCloudKitDemo/DataProvider/CoreDataStack.swift#L103-L134

**Comment by fatbobman** [comment]
你好，我刚试了一下，可以通过。 PersistentHistoryTrackingKitTests 需要一些准备时间，刚才在 Xcode 14.1 + macOS 13 下进行了测试，iOS 和 mac 环境都过了。
<img width="441" alt="image" src="https://user-images.githubusercontent.com/55673881/197764374-e288f319-8f4a-4c72-a412-361cd5d298ef.png">
你能把错误提示贴给我吗？
另外，日期与token没有太大的区别。在内部存储中，transaction 就是保存的日期

**Comment by fatbobman** [comment]
你好，我刚试了一下，可以通过。 PersistentHistoryTrackingKitTests 需要一些准备时间，刚才在 Xcode 14.1 + macOS 13 下进行了测试，iOS 和 mac 环境都过了。
<img width="441" alt="image" src="https://user-images.githubusercontent.com/55673881/197764374-e288f319-8f4a-4c72-a412-361cd5d298ef.png">
你能把错误提示贴给我吗？
另外，日期与token没有太大的区别。在内部存储中，transaction 就是保存的日期

**Comment by hstdt** [comment]
我用Xcode 14.1测试了`iOS 15.5`和`iOS 16.1`的模拟器，都无法通过，日志如下。

操作方式，clone，使用`.swiftpm`中的`package.xcworkspace`直接执行测试

```
Test: testKitInBatchInsert() in PersistentHistoryTrackingKitTests failed on iPad Pro (12.9-inch) (5th generation) 15.5
Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:119: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:119

Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:122: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:122

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:119: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:119

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:122: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:122

PersistentHistoryTrackingKitTests.swift:122 closure #4 in PersistentHistoryTrackingKitTests.testKitInBatchInsert() (PersistentHistoryTrackingKitTests)

PersistentHistoryTrackingKitTests.swift:121 (3) suspend resume partial function for PersistentHistoryTrackingKitTests.testKitInBatchInsert() (PersistentHistoryTrackingKitTests)

Test: testManualCleaner() in PersistentHistoryTrackingKitTests failed on iPad Pro (12.9-inch) (5th generation) 15.5
Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:169: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:169

Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:172: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:172

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:169: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:169

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:172: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:172

Test: testPersistentHistoryKitInAppGroup() in PersistentHistoryTrackingKitTests failed on iPad Pro (12.9-inch) (5th generation) 15.5
Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:62: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:62

Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:65: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:65

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:62: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:62

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:65: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:65

Test: testTwoAppWithKit() in PersistentHistoryTrackingKitTests failed on iPad Pro (12.9-inch) (5th generation) 15.5
Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:226: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:226

Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:230: XCTAssertNotNil failed
File: PersistentHistoryTrackingKitTests.swift:230

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:226: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:226

  Assertions: Assertion Failure at PersistentHistoryTrackingKitTests.swift:230: XCTAssertNotNil failed
  File: PersistentHistoryTrackingKitTests.swift:230


```

**Comment by hstdt** [comment]
直接用Mac为目标是可以的

**Comment by fatbobman** [comment]
你单独测试一下 PersistentHistoryTrackingKitTests.swift 呢？ 我刚才在 14、15、16 下都能通过。这个测试好像对设备的速度有些敏感。速度不够的话，需要调高 tear 的休息时间

**Comment by hstdt** [comment]
单独测试PersistentHistoryTrackingKitTests.swift也不行

时间指的是tearDown里面的sleep么，我改成了5也不行
<details>
  <pre> 
Test Suite 'Selected tests' started at 2022-10-25 20:10:56.929
Test Suite 'PersistentHistoryTrackingKitTests.xctest' started at 2022-10-25 20:10:56.929
Test Suite 'PersistentHistoryTrackingKitTests' started at 2022-10-25 20:10:56.930
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testKitInBatchInsert]' started.
[INFO] : Persistent History Track Kit Start
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:119: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testKitInBatchInsert] : XCTAssertNotNil failed
[INFO] : Persistent History Track Kit Stop
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:122: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testKitInBatchInsert] : XCTAssertNotNil failed
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testKitInBatchInsert]' failed (7.227 seconds).
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testManualCleaner]' started.
[INFO] : Persistent History Track Kit Start
[INFO] : Delete transaction success
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:169: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testManualCleaner] : XCTAssertNotNil failed
[INFO] : Persistent History Track Kit Stop
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:172: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testManualCleaner] : XCTAssertNotNil failed
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testManualCleaner]' failed (7.249 seconds).
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup]' started.
[INFO] : Persistent History Track Kit Start
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:62: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup] : XCTAssertNotNil failed
[INFO] : Persistent History Track Kit Stop
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:65: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup] : XCTAssertNotNil failed
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup]' failed (7.208 seconds).
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testTwoAppWithKit]' started.
[INFO] : Persistent History Track Kit Start
[INFO] : Persistent History Track Kit Start
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:226: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testTwoAppWithKit] : XCTAssertNotNil failed
/Users/tdt/Projects/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:230: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testTwoAppWithKit] : XCTAssertNotNil failed
[INFO] : Persistent History Track Kit Stop
[INFO] : Persistent History Track Kit Stop
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testTwoAppWithKit]' failed (5.126 seconds).
Test Suite 'PersistentHistoryTrackingKitTests' failed at 2022-10-25 20:11:23.741.
	 Executed 4 tests, with 8 failures (0 unexpected) in 26.810 (26.812) seconds
Test Suite 'PersistentHistoryTrackingKitTests.xctest' failed at 2022-10-25 20:11:23.742.
	 Executed 4 tests, with 8 failures (0 unexpected) in 26.810 (26.812) seconds
Test Suite 'Selected tests' failed at 2022-10-25 20:11:23.742.
	 Executed 4 tests, with 8 failures (0 unexpected) in 26.810 (26.813) seconds
Program ended with exit code: 1
</pre>
</details>

**Comment by fatbobman** [comment]
你调一下 116 行的 await sleep(seconds: 2) 时间吧，调长点，看看能否合并成功。合并有延迟，或许同机器效率有关。
看看单独这个测试能否过。我是全部能过，所以不好分析。

**Comment by hstdt** [comment]
还是不行，我先用mac调着试试，后面如果有什么发现我再反馈

**Comment by hstdt** [comment]
不知道是编译器的bug还是什么，在另一台Xcode 14.1 beta3上这行代码会闪退(mac不会且单元测试通过)。实际上在Xcode 14.1/xcode 14.0上这行代码在iOS设备上实际上不会响应`NSPersistentStoreRemoteChange`就在单元测试中Fail掉了，在mac上正常

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/10215098/197775389-fb8deb7e-efb4-4d03-af5b-d2315e0185a3.png">

<img width="1777" alt="image" src="https://user-images.githubusercontent.com/10215098/197775613-40e7db84-2247-423d-99c5-b4c14b356c25.png">

我的`Xcode 14.1是Candidate 1`不是最新的`Candidate 2`，后面我更新下再看看看效果

**Comment by hstdt** [comment]
另一台电脑的 mac 12.6 + Xcode 13.4.1也不行

有一个奇怪的地方是iOS的changed发生在kit初始化之前

iOS
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/10215098/197777951-1a94adf1-d5c9-4a93-a064-937e859246b4.png">

mac
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/10215098/197778930-6fa885df-60d8-4843-bde4-a3dc2eb9f9e5.png">

**Comment by fatbobman** [comment]
你的设备是 m1 吗？我看看是否会是硬件的问题。我在 Xcode 13.4.1 下测试，也没有问题。

**Comment by hstdt** [comment]
是的，两台都是M1. 想起来你另外文章的写法，这样就ok了，sleep全部删掉也正常，但是需要iOS 15+

<img width="1823" alt="image" src="https://user-images.githubusercontent.com/10215098/197781742-174c3ff6-28d2-4ae7-b675-472983e4a576.png">
<details>
  <pre>
Test Suite 'Selected tests' started at 2022-10-25 21:08:51.487
Test Suite 'PersistentHistoryTrackingKitTests.xctest' started at 2022-10-25 21:08:51.487
Test Suite 'PersistentHistoryTrackingKitTests' started at 2022-10-25 21:08:51.488
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testKitInBatchInsert]' started.
[INFO] : Persistent History Track Kit Start
changed!!!
[INFO] : Get a `NSPersistentStoreRemoteChange` notification
[INFO] : The last history transaction timestamp for ["app1", "app2"] is 1/1/01, 8:05:43 AM
[INFO] : There are 1 transactions with 9 changes related to `app1` in the query
[INFO] : merge 1 transactions, update `app1`'s timestamp to 10/25/22, 9:08:51 PM
[INFO] : Delete transaction success
[INFO] : Persistent History Track Kit Stop
2022-10-25 21:08:51.514630+0800 xctest[35847:96934180] [logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/tdt/Library/Developer/CoreSimulator/Devices/6F21A517-D7AC-4C24-94BD-A803380BCC4F/data/Library/Caches/PersistentHistoryKitTestDB.sqlite
2022-10-25 21:08:51.514705+0800 xctest[35847:96934180] [logging] invalidated open fd: 7 (0x11)
2022-10-25 21:08:51.514774+0800 xctest[35847:96934181] [logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/tdt/Library/Developer/CoreSimulator/Devices/6F21A517-D7AC-4C24-94BD-A803380BCC4F/data/Library/Caches/PersistentHistoryKitTestDB.sqlite-wal
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testKitInBatchInsert]' passed (0.027 seconds).
2022-10-25 21:08:51.514815+0800 xctest[35847:96934180] [logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/tdt/Library/Developer/CoreSimulator/Devices/6F21A517-D7AC-4C24-94BD-A803380BCC4F/data/Library/Caches/PersistentHistoryKitTestDB.sqlite-shm
2022-10-25 21:08:51.520139+0800 xctest[35847:96934181] [logging] invalidated open fd: 8 (0x11)
2022-10-25 21:08:51.520142+0800 xctest[35847:96934180] [logging] invalidated open fd: 9 (0x11)
Test Suite 'PersistentHistoryTrackingKitTests' passed at 2022-10-25 21:08:51.520.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.027 (0.033) seconds
Test Suite 'PersistentHistoryTrackingKitTests.xctest' passed at 2022-10-25 21:08:51.521.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.027 (0.034) seconds
Test Suite 'Selected tests' passed at 2022-10-25 21:08:51.521.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.027 (0.034) seconds
 </pre>
</details>

**Comment by fatbobman** [comment]
从你这个顺序看，应该是响应 notification 的 task 启动的慢了。
我故意不用异步的操作，这种操作无法保证每次的时间线都完全一致。
你可以试一下 在 batch 前面添加一个 sleep ，然后仍然用 perforAndWait 试一下。
<img width="454" alt="image" src="https://user-images.githubusercontent.com/55673881/197782907-67f23b95-2a0e-458a-9510-b39396186e59.png">

或许 m1 的多线程的执行上与 intel 还是有一点区别的。

**Comment by hstdt** [comment]
试过的，这样顺序对了，但是还是fail

**Comment by hstdt** [comment]
问题看起来应该是`performAndWait`和`sequence`在M1上有问题，也不知道是否是编译器bug，因为Xcode 14.1 beta3直接闪退，可能是在修?

**Comment by fatbobman** [comment]
看来是，明天我调整一下吧。 把  sequence 换成苹果的异步库的解决方案。

**Comment by fatbobman** [comment]
用 publisher.values + 苹果的异步库 也可以实现一样的效果。不过系统需求就变成 15+ 了

**Comment by hstdt** [comment]
> 用 publisher.values + 苹果的异步库 也可以实现一样的效果。不过系统需求就变成 15+ 了
 
@fatbobman  按照这个思路实现了一下，还是不通过，那应该就不是`sequence`的问题了

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/10215098/197919756-7618b8f7-7124-4329-8870-2b18fa91e4c5.png">

**Comment by hstdt** [comment]
苹果demo的实现还是使用的`OperationQueue `

https://github.com/hstdt/AppleSamples/blob/d66a7ad5a4c8bb1d8bfd265c597ed6d2bf2c3ae4/SynchronizingALocalStoreToTheCloud/CoreDataCloudKitDemo/DataProvider/CoreDataStack.swift#L136-L143

**Comment by fatbobman** [comment]
直接使用 values 不行。会丢内容。需要配合苹果的异步库（ https://github.com/apple/swift-async-algorithms ），为 values 添加 buffer

**Comment by hstdt** [comment]
先简单加了个，这样对么。单元测试还是不通过，主要是确认`performAndWait`和Task+Notification Publisher这种方式就会有冲突吧。但是貌似performAndWait不能换。

await perform 和 Task+Notification Publisher 两种方案都能通过单元测试，但是系统最低要求绕不过去。而且就算提高了系统版本，开发者自己用也会有问题的...

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/10215098/197921739-bf5eeef3-bd3a-4935-9255-c01e2d9fd47e.png">

**Comment by fatbobman** [comment]
其实现在的库已经有不少人在生产环境中使用了，没有遇到你出现的问题。我刚才新增了以branch 。 换成苹果的异步库，系统需求要 iOS 15+
[async-algorithms](https://github.com/fatbobman/PersistentHistoryTrackingKit/tree/async-algorithms)

**Comment by hstdt** [comment]
async-algorithms是代码没提交么，这个分支没有新内容...

~~如果用performAndWait的话，`XCTAssert`不能立刻执行，刚试了一下这样就可以了。所以生产环境应该不会有问题~~

<img width="1825" alt="image" src="https://user-images.githubusercontent.com/10215098/197924871-7d0bb7a9-dde0-4732-ab2f-ba85978c437a.png">

代码不对，没有执行到assert，增加了sleep之后就失败了

<img width="1817" alt="image" src="https://user-images.githubusercontent.com/10215098/197925566-fa3fc3b9-98ed-417a-9caf-c500c870f87f.png">

不响应通知但是不报错，感觉是最麻烦的事情...

**Comment by fatbobman** [comment]
用 new branch

**Comment by hstdt** [comment]
还是失败，如果只用`performAndWait`，可能会一直不响应吧..但是如果用其他的比如perform或者cloudkit，就可能被其他的带动触发检查

<img width="1883" alt="image" src="https://user-images.githubusercontent.com/10215098/197927627-048c580c-810e-4233-bf04-2bbbf071cd45.png">

**Comment by hstdt** [comment]
换成perform也不行(mac还是可以通过😥)

<img width="1815" alt="image" src="https://user-images.githubusercontent.com/10215098/197928561-843b4d90-2e82-4c6b-af97-d74704e53737.png">

<details>
  <pre> 
Test Suite 'Selected tests' started at 2022-10-26 11:38:02.142
Test Suite 'PersistentHistoryTrackingKitTests.xctest' started at 2022-10-26 11:38:02.142
Test Suite 'PersistentHistoryTrackingKitTests' started at 2022-10-26 11:38:02.142
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup]' started.
[INFO] : Persistent History Track Kit Start
/Users/tdt/Downloads/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:63: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup] : XCTAssertNotNil failed
/Users/tdt/Downloads/PersistentHistoryTrackingKit/Tests/PersistentHistoryTrackingKitTests/PersistentHistoryTrackingKitTests.swift:66: error: -[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup] : XCTAssertNotNil failed
[INFO] : Persistent History Track Kit Stop
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup]' failed (7.183 seconds).
Test Suite 'PersistentHistoryTrackingKitTests' failed at 2022-10-26 11:38:09.326.
	 Executed 1 test, with 2 failures (0 unexpected) in 7.183 (7.183) seconds
Test Suite 'PersistentHistoryTrackingKitTests.xctest' failed at 2022-10-26 11:38:09.326.
	 Executed 1 test, with 2 failures (0 unexpected) in 7.183 (7.184) seconds
Test Suite 'Selected tests' failed at 2022-10-26 11:38:09.327.
	 Executed 1 test, with 2 failures (0 unexpected) in 7.183 (7.185) seconds
Program ended with exit code: 1
  </pre>
</details>

**Comment by fatbobman** [comment]
这段代码是从上下文中获取一个 id ，用来判断数据是否被合并到了上下文。无论 同步还是异步，都不会造成系统卡顿。perform 的目的是让代码确定在上下文的线程中执行。

你现在碰到的问题是，同步的信息在 合并处理代码之前就发送了。因此，perform 没有在当前上下文中找到对应的id，测试失败。

因此，我之前让你在 kit 启动后 和  batch操作前等待一段时间，保证 task 在合并消息来临之前完成启动。

但是，在我的设备和其他使用者哪里，都没有遇到你目前出现的问题。这才是奇怪的。
无论是我以前自己写的 Publisher 还是换成 苹果的异步库，目的都是对 notification 进行串行处理。苹果demo 使用 opreatorQueue 也一样。避免同时进行多个合并操作

**Comment by hstdt** [comment]
应该不是之前发送，是Publisher在iOS设备上不响应`NSPersistentStoreRemoteChange`，把Notification放在外面是收的到的，但是在Task里面就收不到了

我把start放在MainActor里面顺序就对了

<img width="1793" alt="image" src="https://user-images.githubusercontent.com/10215098/197931212-6e453ac4-1fc0-4b7a-acbe-6e9b7c7fe659.png">

**Comment by fatbobman** [comment]
在你在  return objectID 前打印一下 id ，我怀疑你的 id 是临时id ，和下面的对不上

**Comment by hstdt** [comment]
lastTimestamp为nil应该就能说明没有响应

<img width="1804" alt="image" src="https://user-images.githubusercontent.com/10215098/197931953-3d66ad77-586f-40ef-8094-0cb2c882e4bb.png">

**Comment by fatbobman** [comment]
实在搞不清楚为什么在你那里会这样。我无法重现你的问题，因此很难做出判断。你可以把日志级别开高 设置成 3 ，看看是否有处理事件

**Comment by hstdt** [comment]
单元测试里已经是3了

**Comment by fatbobman** [comment]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/55673881/197932338-bab725fb-fabf-4d34-9e61-634f885b9fd9.png">
两个版本的代码下，我都会收到信息

**Comment by hstdt** [comment]
mac上是能收到，就是这个很尴尬。所有在Publisher响应里面的代码都没有执行

<details>
  <pre> 
Test Suite 'Selected tests' started at 2022-10-26 12:10:14.265
Test Suite 'PersistentHistoryTrackingKitTests.xctest' started at 2022-10-26 12:10:14.265
Test Suite 'PersistentHistoryTrackingKitTests' started at 2022-10-26 12:10:14.266
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup]' started.
[INFO] : Persistent History Track Kit Start
[INFO][Test]event.objectID:x-coredata://46479560-2637-4467-8224-69FAF724BA32/Event/p1
[INFO][Test]changed!!!
[INFO][Test]changed!!!
[INFO] : Get a `NSPersistentStoreRemoteChange` notification
[INFO] : The last history transaction timestamp for ["app1", "app2"] is 1/1/1 08:05:43
[INFO] : There are 1 transactions with 1 changes related to `app1` in the query
[INFO] : merge 1 transactions, update `app1`'s timestamp to 2022/10/26 12:10:14
[INFO] : Delete transaction success
[INFO][Test]event.objectID:x-coredata://46479560-2637-4467-8224-69FAF724BA32/Event/p1
[INFO] : Persistent History Track Kit Stop
Test Case '-[PersistentHistoryTrackingKitTests.PersistentHistoryTrackingKitTests testPersistentHistoryKitInAppGroup]' passed (5.096 seconds).
Test Suite 'PersistentHistoryTrackingKitTests' passed at 2022-10-26 12:10:19.362.
	 Executed 1 test, with 0 failures (0 unexpected) in 5.096 (5.096) seconds
Test Suite 'PersistentHistoryTrackingKitTests.xctest' passed at 2022-10-26 12:10:19.362.
	 Executed 1 test, with 0 failures (0 unexpected) in 5.096 (5.097) seconds
Test Suite 'Selected tests' passed at 2022-10-26 12:10:19.363.
	 Executed 1 test, with 0 failures (0 unexpected) in 5.096 (5.098) seconds
Program ended with exit code: 0
</pre>
</details>

**Comment by fatbobman** [comment]
我在所有模拟器上都可以。怀疑是 m1 下模拟器的 bug

**Comment by hstdt** [comment]
> 我在所有模拟器上都可以。怀疑是 m1 下模拟器的 bug

有很大可能，我在实际项目中再看看

**Comment by hstdt** [comment]
> 我在所有模拟器上都可以。怀疑是 m1 下模拟器的 bug

按照这个想法，我用Catalyst不通过，用Catalyst with Rosetta通过

**Comment by hstdt** [comment]
issue我先关掉了，后续如果有发现再沟通
